name: Daily AI Training

on:
  schedule:
    - cron: '0 7 * * *'  # every day at 7 AM UTC
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run AI Script
        run: python pig_ai_model.py

